version: "2"
run:
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
    json:
      path: stderr
    checkstyle:
      path: go-report.xml
linters:
  default: none
  enable:
    - depguard
    - dupl
    - errcheck
    - gochecknoinits
    # - gochecknoglobals
    - goconst
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - revive
    - staticcheck
  # disable:
  #   - wsl
  #   - nlreturn
  #   - err113
  #   - exhaustruct
  #   - gochecknoglobals
  #   - ireturn
  #   - nonamedreturns
  #   - varnamelen
  #   - wrapcheck
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/sirupsen/logrus
              desc: logging is allowed only by the local log package
            - pkg: logutils.Log
              desc: logging is allowed only by the local log package
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    govet:
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    lll:
      line-length: 120
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    revive:
      rules:
        - name: unused-parameter
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      module-path: github.tools.sap/AI/forest-workload-operator/components/workload-operator
    goimports:
      local-prefixes:
        - github.com/golangci/golangci-lint
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
