
project_name: coco
builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
    main: ./cmd/coco/
    ldflags:
      - -extldflags '-static'
      - -s -w 
      - -X github.com/configuration-tools-for-gitops/pkg/version.version={{.Version}}
      - -X github.com/configuration-tools-for-gitops/pkg/version.gitCommit={{.Commit}}
      - -X github.com/configuration-tools-for-gitops/pkg/version.buildDate={{.Date}}
      - -X github.com/configuration-tools-for-gitops/pkg/version.gitTreeState=clean


archives:
  - format: binary
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_checksums.txt'

