name: Linting

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
permissions:
  contents: read

jobs:
  variables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: golangci version
        uses: mikefarah/yq@v4.33.1
        id: golangci_version
        with:
          cmd: yq '.golangci_version' build/vars.yml
      - name: golang version
        uses: mikefarah/yq@v4.33.1
        id: go_version
        with:
          cmd: yq '.go_version' build/vars.yml
    outputs:
      go_version: ${{ steps.go_version.outputs.result }}
      golangci_version: ${{ steps.golangci_version.outputs.result }}
  run-lint:
    runs-on: ubuntu-latest
    needs: [variables]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        # https://github.com/marketplace/actions/setup-go-environment
        with:
          go-version: ${{ needs.variables.outputs.go_version }}
          cache: false
      - name: Debug-vars
        run: echo "github workspace ${{ github.workspace }}/build/.golangci.yml"
      - name: Run golangci-lint
        # https://github.com/marketplace/actions/run-golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ needs.variables.outputs.golangci_version }}
          args: |
            --timeout 10m
            --config ${{ github.workspace }}/build/.golangci.yml

