name: Linting

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
permissions:
  contents: read

jobs:
  variables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: golangci version
        uses: mikefarah/yq@v4.33.1
        id: golangci_version
        with:
          cmd: yq '.golangci_version' build/vars.yml
      - name: golang version
        uses: mikefarah/yq@v4.33.1
        id: go_version
        with:
          cmd: yq '.go_version' build/vars.yml
      - name: Debug-vars
        run: echo "goVersion ${{ steps.go_version.outputs.result }}, golangciVersion ${{ steps.golangci_version.outputs.result }}"
    outputs:
      go_version: ${{ steps.go_version.outputs.result }}
      golangci_version: ${{ steps.golangci_version.outputs.result }}
  run-lint:
    runs-on: ubuntu-latest
    needs: [variables]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Debug-vars
        run: echo "goVersion ${{ needs.variables.outputs.go_version }}, golangciVersion ${{ needs.variables.outputs.golangci_version }}"
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ needs.variables.outputs.go_version }}
          cache: false
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          # skip-go-installation: true
          version: ${{ needs.variables.outputs.golangci_version }}
          args: --timeout 10m

